server:
  port: 8443
  ssl:
    key-store-password: tomcat
    key-store: classpath:mykeystore.p12
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  data:
    mongodb:
      database: user_db
      port: 27017
      host: localhost

  security:
    user:
      name: test
      password: test