jwt:
  secret: thx5lf4VQmTcK_O0d0uFpfO-S-0KgnLAClGoG9boA375f7DThJISO-asDSHGzLb9YNbl60594IHvKwiyj7cPTgt5841lVt5P3bd1rXI_tF2WWXT_Gfs-0l4s3zO2h7ivC6oeY5NW1ELDCu9_sO9GTsvnfW1lzYO6VTGVp3ZOU-0DWgGKfSyCOHvUKgB23qt7McZhrzrj7wpNqw8otPrtQgT_RXHYLNHaXyIg5DdlZg7o3mTU2jr0pHmZLCsaY6ZaqcyiYsysdqELiz-c2Ef9OdznpSF3e5li1IksWcqPXmEvxWOeSSsGXEwi0O_ivCXBJTpKC7Bqs_GnBn7I7ZD9PQ
email:
  custom-password: Amar@12345

server:
  port: 8443
  ssl:
    key-store-password: tomcat
    key-store: classpath:mykeystore.p12
    key-store-type: PKCS12
    key-alias: tomcat
#  error:
#    whitelabel:
#      enabled: false

spring:
  data:
    mongodb:
      database: user_db
      port: 27017
      host: localhost
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 3MB
  #  datasource:
#    url: jdbc:mongodb://localhost/user_db
#    driver-class-name: class-name=mongodb.jdbc.MongoDriver
  security:
    user:
      name: test
      password: test
# custom handling /error for spring
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false